### ISSUE TITLE
Licensing issue with `copyRuntimeClasses` option

### ISSUE THREAD

**Issue by NebelNidas** [RaphiMC/JavaDowngrader#9]
Adding the LGPL-licensed `runtime-dep` classes directly into the output JAR creates a bit of a licensing issue, since section 4d) of the LGPL requires consumers to provide a way of re-linking their program with modified JavaDowngrader binaries. Meaning that consumers are now forced to either release their own application under a LGPL-compatible license as well, or provide instructions on how to replace the affected files within the JAR, which is inconvenient.
Switching the `runtime-dep` classes to a more permissive license would make things less legally troubling for JavaDowngrader users.

**Comment by RaphiMC** [comment]
Yeah sure I would be ok with this change. Is the MIT license fine for runtime-dep?

**Comment by Gaming32** [comment]
Yeah, I think MIT is permissive enough. The other worry is that some of these methods come from the GPL-licensed OpenJDK.

**Comment by RaphiMC** [comment]
Hmm right, we would have to solve that issue first

**Comment by RaphiMC** [comment]
Version 1.0.1-SNAPSHOT has the runtime-dep module now licensed under MIT
